apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop   # lowercase
  labels:
    app: nginx          # labels must be key-value pairs
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
